- name: Check if Docker is installed
  command: systemctl status docker
  register: docker_check
  ignore_errors: yes
  changed_when: no

- name: Download the Docker installer
  get_url:
    url: https://get.docker.com/
    dest: /root/install_docker.sh
    mode: 0700
  when: docker_check.stderr.find('service could not be found') != -1

- name: Install Docker
  shell: /root/install_docker.sh
  when: docker_check.stderr.find('service could not be found') != -1

- name: Remove the Docker installer file.
  file:
    state: absent
    path: /root/install_docker.sh

- name: Enable the Docker daemon in systemd
  systemd:
    name: docker
    enabled: yes
    masked: no
    state: started

- name: Check if Docker Compose is installed
  command: docker-compose --version
  register: docker_compose_check
  ignore_errors: yes
  changed_when: no

- name: Download and install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.21.2/docker-compose-Linux-x86_64
    dest: /usr/bin/docker-compose
    mode: 0755
  when:
    - docker_compose_check.msg is defined
    - docker_compose_check.msg.find('No such file or directory') != -1
