[package]
name = "binance-access"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "*"
dotenv_codegen = "*"
binance = { git = "https://github.com/wisespace-io/binance-rs.git" }

